// S Exclusive - Configuration File
const CONFIG = {
  brandName: "S Exclusive",
  logoUrl: "images/logo.webp",
  callChatUrl: "https://tinyurl.com/vnju2d6s",
  copyrightText: "© 2026 S Exclusive. All copyright rights reserved.",
  profiles: [
    {
        "id": "p_01",
        "name": "Freja Nielsen",
        "location": "Copenhagen, Denmark",
        "city": "Copenhagen",
        "country": "Denmark",
        "countryCode": "DK",
        "image": "images/card_01.jpg",
        "online": true
    },
    {
        "id": "p_02",
        "name": "Charlotte Hayes",
        "location": "Sydney, Australia",
        "city": "Sydney",
        "country": "Australia",
        "countryCode": "AU",
        "image": "images/card_02.jpg",
        "online": true
    },
    {
        "id": "p_03",
        "name": "Olivia Whitmore",
        "location": "Manchester, UK",
        "city": "Manchester",
        "country": "UK",
        "countryCode": "GB",
        "image": "images/card_03.jpg",
        "online": true
    },
    {
        "id": "p_04",
        "name": "Giulia Conti",
        "location": "Milan, Italy",
        "city": "Milan",
        "country": "Italy",
        "countryCode": "IT",
        "image": "images/card_04.jpg",
        "online": true
    },
    {
        "id": "p_05",
        "name": "Lucia Herrera",
        "location": "Madrid, Spain",
        "city": "Madrid",
        "country": "Spain",
        "countryCode": "ES",
        "image": "images/card_05.jpg",
        "online": true
    },
    {
        "id": "p_06",
        "name": "Olivia Reeves",
        "location": "Los Angeles, USA",
        "city": "Los Angeles",
        "country": "USA",
        "countryCode": "US",
        "image": "images/card_06.jpg",
        "online": true
    },
    {
        "id": "p_07",
        "name": "Lily Tremblay",
        "location": "Toronto, Canada",
        "city": "Toronto",
        "country": "Canada",
        "countryCode": "CA",
        "image": "images/card_07.jpg",
        "online": true
    },
    {
        "id": "p_08",
        "name": "Amelia Parker",
        "location": "London, UK",
        "city": "London",
        "country": "UK",
        "countryCode": "GB",
        "image": "images/card_08.jpg",
        "online": true
    },
    {
        "id": "p_09",
        "name": "Sofia Caruso",
        "location": "Rome, Italy",
        "city": "Rome",
        "country": "Italy",
        "countryCode": "IT",
        "image": "images/card_09.jpg",
        "online": true
    },
    {
        "id": "p_10",
        "name": "Helena Costa",
        "location": "São Paulo, Brazil",
        "city": "São Paulo",
        "country": "Brazil",
        "countryCode": "BR",
        "image": "images/card_10.jpg",
        "online": true
    },
    {
        "id": "p_11",
        "name": "Eliška Novak",
        "location": "Prague, Czechia",
        "city": "Prague",
        "country": "Czechia",
        "countryCode": "CZ",
        "image": "images/card_11.jpg",
        "online": true
    },
    {
        "id": "p_12",
        "name": "Camille Duval",
        "location": "Paris, France",
        "city": "Paris",
        "country": "France",
        "countryCode": "FR",
        "image": "images/card_12.jpg",
        "online": true
    },
    {
        "id": "p_13",
        "name": "Hannah Richter",
        "location": "Berlin, Germany",
        "city": "Berlin",
        "country": "Germany",
        "countryCode": "DE",
        "image": "images/card_13.jpg",
        "online": true
    },
    {
        "id": "p_14",
        "name": "Emma Laurent",
        "location": "Vancouver, Canada",
        "city": "Vancouver",
        "country": "Canada",
        "countryCode": "CA",
        "image": "images/card_14.jpg",
        "online": true
    },
    {
        "id": "p_15",
        "name": "Isabel Duarte",
        "location": "Porto, Portugal",
        "city": "Porto",
        "country": "Portugal",
        "countryCode": "PT",
        "image": "images/card_15.jpg",
        "online": true
    },
    {
        "id": "p_16",
        "name": "Freya Lindholm",
        "location": "Stockholm, Sweden",
        "city": "Stockholm",
        "country": "Sweden",
        "countryCode": "SE",
        "image": "images/card_16.jpg",
        "online": true
    },
    {
        "id": "p_17",
        "name": "Clara Weiss",
        "location": "Vienna, Austria",
        "city": "Vienna",
        "country": "Austria",
        "countryCode": "AT",
        "image": "images/card_17.jpg",
        "online": true
    },
    {
        "id": "p_18",
        "name": "Natalia Zielinska",
        "location": "Krakow, Poland",
        "city": "Krakow",
        "country": "Poland",
        "countryCode": "PL",
        "image": "images/card_18.jpg",
        "online": true
    },
    {
        "id": "p_19",
        "name": "Elise Vermeer",
        "location": "Amsterdam, Netherlands",
        "city": "Amsterdam",
        "country": "Netherlands",
        "countryCode": "NL",
        "image": "images/card_19.jpg",
        "online": true
    },
    {
        "id": "p_20",
        "name": "Lucia Navarro",
        "location": "Valencia, Spain",
        "city": "Valencia",
        "country": "Spain",
        "countryCode": "ES",
        "image": "images/card_20.jpg",
        "online": true
    },
    {
        "id": "p_21",
        "name": "Maeve Sullivan",
        "location": "Dublin, Ireland",
        "city": "Dublin",
        "country": "Ireland",
        "countryCode": "IE",
        "image": "images/card_21.jpg",
        "online": true
    },
    {
        "id": "p_22",
        "name": "Sophie Laurent",
        "location": "Montreal, Canada",
        "city": "Montreal",
        "country": "Canada",
        "countryCode": "CA",
        "image": "images/card_22.jpg",
        "online": true
    },
    {
        "id": "p_23",
        "name": "桜井 美月",
        "location": "京都市, 日本",
        "city": "京都市",
        "country": "日本",
        "countryCode": "JP",
        "image": "images/card_23.jpg",
        "online": true
    },
    {
        "id": "p_24",
        "name": "森川 彩花",
        "location": "横浜市, 日本",
        "city": "横浜市",
        "country": "日本",
        "countryCode": "JP",
        "image": "images/card_24.jpg",
        "online": true
    },
    {
        "id": "p_25",
        "name": "岡田 詩織",
        "location": "札幌市, 日本",
        "city": "札幌市",
        "country": "日本",
        "countryCode": "JP",
        "image": "images/card_25.jpg",
        "online": true
    },
    {
        "id": "p_26",
        "name": "西村 遥",
        "location": "福岡市, 日本",
        "city": "福岡市",
        "country": "日本",
        "countryCode": "JP",
        "image": "images/card_26.jpg",
        "online": true
    },
    {
        "id": "p_27",
        "name": "石川 琴音",
        "location": "金沢市, 日本",
        "city": "金沢市",
        "country": "日本",
        "countryCode": "JP",
        "image": "images/card_27.jpg",
        "online": true
    },
    {
        "id": "p_28",
        "name": "松本 莉子",
        "location": "神戸市, 日本",
        "city": "神戸市",
        "country": "日本",
        "countryCode": "JP",
        "image": "images/card_28.jpg",
        "online": true
    },
    {
        "id": "p_29",
        "name": "藤原 菜月",
        "location": "仙台市, 日本",
        "city": "仙台市",
        "country": "日本",
        "countryCode": "JP",
        "image": "images/card_29.jpg",
        "online": true
    },
    {
        "id": "p_30",
        "name": "中川 真帆",
        "location": "長崎市, 日本",
        "city": "長崎市",
        "country": "日本",
        "countryCode": "JP",
        "image": "images/card_30.jpg",
        "online": true
    }
],
  translations: {
    "en": {
        "code": "EN",
        "label": "English",
        "native": "English",
        "onlineHeadline": "50+ Girls Online Here",
        "onlineSub": "WhatsApp 👇",
        "btnText": "WhatsApp",
        "connecting": "Opening WhatsApp...",
        "priorityCountries": [
            "US",
            "GB",
            "AU",
            "CA",
            "IE",
            "DK",
            "SE",
            "NL",
            "DE",
            "FR",
            "IT",
            "ES",
            "CZ",
            "PL",
            "AT",
            "PT",
            "BR",
            "JP"
        ]
    },
    "pt": {
        "code": "PT",
        "label": "Português",
        "native": "Português",
        "onlineHeadline": "50+ Girls Online Here",
        "onlineSub": "WhatsApp 👇",
        "btnText": "WhatsApp",
        "connecting": "Opening WhatsApp...",
        "priorityCountries": [
            "PT",
            "BR",
            "ES",
            "IT",
            "FR",
            "US",
            "GB",
            "AU",
            "CA",
            "DE",
            "CZ",
            "JP"
        ]
    },
    "es": {
        "code": "ES",
        "label": "Español",
        "native": "Español",
        "onlineHeadline": "50+ Girls Online Here",
        "onlineSub": "WhatsApp 👇",
        "btnText": "WhatsApp",
        "connecting": "Opening WhatsApp...",
        "priorityCountries": [
            "ES",
            "PT",
            "BR",
            "IT",
            "FR",
            "US",
            "GB",
            "AU",
            "CA",
            "DE",
            "CZ",
            "JP"
        ]
    },
    "it": {
        "code": "IT",
        "label": "Italiano",
        "native": "Italiano",
        "onlineHeadline": "50+ Girls Online Here",
        "onlineSub": "WhatsApp 👇",
        "btnText": "WhatsApp",
        "connecting": "Opening WhatsApp...",
        "priorityCountries": [
            "IT",
            "FR",
            "ES",
            "PT",
            "BR",
            "DE",
            "AT",
            "US",
            "GB",
            "AU",
            "CA",
            "CZ",
            "JP"
        ]
    },
    "fr": {
        "code": "FR",
        "label": "Français",
        "native": "Français",
        "onlineHeadline": "50+ Girls Online Here",
        "onlineSub": "WhatsApp 👇",
        "btnText": "WhatsApp",
        "connecting": "Opening WhatsApp...",
        "priorityCountries": [
            "FR",
            "CA",
            "IT",
            "ES",
            "PT",
            "BR",
            "DE",
            "GB",
            "US",
            "AU",
            "CZ",
            "JP"
        ]
    },
    "de": {
        "code": "DE",
        "label": "Deutsch",
        "native": "Deutsch",
        "onlineHeadline": "50+ Girls Online Here",
        "onlineSub": "WhatsApp 👇",
        "btnText": "WhatsApp",
        "connecting": "Opening WhatsApp...",
        "priorityCountries": [
            "DE",
            "AT",
            "DK",
            "NL",
            "SE",
            "CZ",
            "PL",
            "FR",
            "IT",
            "ES",
            "GB",
            "US",
            "CA",
            "AU",
            "JP"
        ]
    },
    "da": {
        "code": "DA",
        "label": "Dansk",
        "native": "Dansk",
        "onlineHeadline": "50+ Girls Online Here",
        "onlineSub": "WhatsApp 👇",
        "btnText": "WhatsApp",
        "connecting": "Opening WhatsApp...",
        "priorityCountries": [
            "DK",
            "SE",
            "DE",
            "NL",
            "GB",
            "US",
            "CA",
            "AU",
            "FR",
            "IT",
            "ES",
            "CZ",
            "JP"
        ]
    },
    "cs": {
        "code": "CS",
        "label": "Čeština",
        "native": "Čeština",
        "onlineHeadline": "50+ Girls Online Here",
        "onlineSub": "WhatsApp 👇",
        "btnText": "WhatsApp",
        "connecting": "Opening WhatsApp...",
        "priorityCountries": [
            "CZ",
            "PL",
            "AT",
            "DE",
            "DK",
            "SE",
            "NL",
            "IT",
            "FR",
            "ES",
            "GB",
            "US",
            "CA",
            "AU",
            "JP"
        ]
    },
    "ja": {
        "code": "JA",
        "label": "日本語",
        "native": "日本語",
        "onlineHeadline": "50+ Girls Online Here",
        "onlineSub": "WhatsApp 👇",
        "btnText": "WhatsApp",
        "connecting": "Opening WhatsApp...",
        "priorityCountries": [
            "JP",
            "US",
            "AU",
            "GB",
            "CA",
            "FR",
            "IT",
            "DE",
            "DK"
        ]
    },
    "id": {
        "code": "ID",
        "label": "Indonesia",
        "native": "Bahasa Indonesia",
        "onlineHeadline": "50+ Girls Online Here",
        "onlineSub": "WhatsApp 👇",
        "btnText": "WhatsApp",
        "connecting": "Opening WhatsApp...",
        "priorityCountries": [
            "JP",
            "AU",
            "US",
            "GB",
            "CA",
            "DK",
            "FR",
            "DE",
            "IT",
            "ES"
        ]
    },
    "fil": {
        "code": "FIL",
        "label": "Philippines",
        "native": "Filipino",
        "onlineHeadline": "50+ Girls Online Here",
        "onlineSub": "WhatsApp 👇",
        "btnText": "WhatsApp",
        "connecting": "Opening WhatsApp...",
        "priorityCountries": [
            "US",
            "CA",
            "AU",
            "GB",
            "JP",
            "DK",
            "FR",
            "DE",
            "IT",
            "ES"
        ]
    },
    "hi": {
        "code": "HI",
        "label": "हिन्दी",
        "native": "हिन्दी",
        "onlineHeadline": "50+ Girls Online Here",
        "onlineSub": "WhatsApp 👇",
        "btnText": "WhatsApp",
        "connecting": "Opening WhatsApp...",
        "priorityCountries": [
            "US",
            "GB",
            "AU",
            "CA",
            "IE",
            "DK",
            "DE",
            "FR",
            "IT",
            "ES",
            "JP"
        ]
    }
}
};
